#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
if (git status | grep 'grep packages/mock'); then
  echo "mock changed"
  npx lerna run test:badge --scope @zidong/dc-mock
  git add packages/mock/README.md
fi
